# Generated by Django 3.2 on 2021-04-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_detallepedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='localizacion',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.localizacion'),
        ),
    ]
